//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineFoodOrdering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coeficent
    {
        public int cprice { get; set; }
        public System.TimeSpan time_set { get; set; }
        public int code { get; set; }
    
        public virtual food food { get; set; }
    }
}
