//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineFoodOrdering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.ordering = new HashSet<ordering>();
        }
    
        public string username { get; set; }
        public string email { get; set; }
        public int post_code { get; set; }
        public long c_cellphone_number { get; set; }
        public Nullable<bool> vegeterian { get; set; }
        public int c_phone_number { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string c_address { get; set; }
        public string c_city { get; set; }
        public string c_province { get; set; }
        public byte[] picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordering> ordering { get; set; }
    }
}
