//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineFoodOrdering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public delivery()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int code { get; set; }
        public string d_name { get; set; }
        public long d_phone_number { get; set; }
        public int resturant { get; set; }
        public bool available { get; set; }
    
        public virtual resturant resturant1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
    }
}
