//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineFoodOrdering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinR
    {
        public int rcode { get; set; }
        public Nullable<byte> point { get; set; }
        public byte[] picture { get; set; }
        public bool @new { get; set; }
        public int fcode { get; set; }
    
        public virtual food food { get; set; }
        public virtual resturant resturant { get; set; }
    }
}
