//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineFoodOrdering.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class resturantEntities : DbContext
    {
        public resturantEntities()
            : base("name=resturantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<coeficent> coeficent { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<delivery> delivery { get; set; }
        public virtual DbSet<food> food { get; set; }
        public virtual DbSet<mambership> mambership { get; set; }
        public virtual DbSet<manager> manager { get; set; }
        public virtual DbSet<manages> manages { get; set; }
        public virtual DbSet<ordering> ordering { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<payment> payment { get; set; }
        public virtual DbSet<resturant> resturant { get; set; }
        public virtual DbSet<work_time> work_time { get; set; }
    }
}
