//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineFoodOrdering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manages
    {
        public int ssn { get; set; }
        public int rcode { get; set; }
        public bool available { get; set; }
        public System.TimeSpan startDate { get; set; }
    
        public virtual manager manager { get; set; }
        public virtual resturant resturant { get; set; }
    }
}
