//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineFoodOrdering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_time
    {
        public int Rcode { get; set; }
        public System.TimeSpan Wtime { get; set; }
    
        public virtual resturant resturant { get; set; }
    }
}
